### PR TITLE
ttbar xsec correction

### PR DESCRIPTION
**Pull request by jec429**
The actual cross-section for the ttbar sample should be 10.5% of the total cross-section taken from the NNLO twiki (815.96 pb-1) so it should be 8.567e+01 pb-1 to account for taus.

### CODE REVIEW

**Comment by skalafut** [comment]
That's good news!  We are off by ~40% in the emu data/TTBar M_EMu
distribution, and this would certainly correct for that discrepancy.
Currently we use a cross sxn of about 56 pb.


Regards,
Sean Kalafut

Physics PhD candidate
University of Minnesota Twin Cities

**Comment by shervin86** [comment]
How the 10.5% is estimated?

**Comment by skalafut** [comment]
See slide 4 of David Morse's presentation:

https://indico.cern.ch/event/491932/contributions/2011775/attachments/1220849/1784766/02012016_JetsX_LQ2_FullStatusUpdate_Morse.pdf

and slide 6 of Abdollah's presentation:

https://indico.cern.ch/event/522930/contributions/2141851/attachments/1266712/1875391/TauTauJJ_FullRep_Abdollah.pdf

both were presented in Jets+X meetings in the past 3 months, and both use
the same cross section of 89.07 pb to normalize the TTJets_DiLept dataset
which we also use.


Regards,
Sean Kalafut

Physics PhD candidate
University of Minnesota Twin Cities

**Comment by jec429** [comment]
Taken from PDG:
http://pdg.arsip.lipi.go.id/2013/reviews/rpp2012-rev-top-quark.pdf

**Comment by shervin86** [comment]
Ok, thanks for the infos. I'm then really worried about what the standard GenXsec script returns.... can someone review all the cross-sections? Sean has already updated the cross-section for the TTbar sample, so I'm closing this PR

**Comment by skalafut** [comment]
cross sections (in pb) from public presentations or analysis notes which
use the same MC datasets as us are on the left, our cross sections in
configs/datasets.dat are on the right.  For some processes I found a cross
section which the EXO MC contact Steve Mrenna recommended using, which was
calculated using a large number of events simulated with FEWZ or MCFM.
Those numbers, when available, are shown in *bold*.  Many of our MC samples
have phase space cuts which are not identical to the samples generated with
FEWZ or MCFM, and thus a valid comparison is not possible.

ZZ pythia (no gamma*):    16.91    10.15
WZ pythia (no gamma*):   45.01    23.40
DYToEE M>50 powheg:    *  -         *1803     *2008.4*
DYToEE or MuMu mass binned powheg:  all consistent with Z'->LL analysis

DYJetsToLL amcnlo
M>50 (dominated by zero jet):  -          5915
*6025.2**
DYJetsToLL madgraph
M>50 (dominated by zero jet):  -          5991

*6025.2**
Most of the DYJetsToLL events have no quarks or gluons from the hard
interaction at GEN level, so in principle these datasets could be
normalized to the Z/gamma* -> LL (M_LL > 50) cross section.



Regards,
Sean Kalafut

Physics PhD candidate
University of Minnesota Twin Cities

**Pull request closed without merging**
