### PR TITLE
Remove Rochester corrections from MiniTTree production

### PR DESCRIPTION
**Pull request by jec429**
This PR corresponds to issue #47

### CODE REVIEW

**Comment by shervin86** [comment]
I just realized that the scaleCorrectedMuons are not used in the miniTree production. The wRleadingMuon and wRsubleading muon are not used anymore, only the wRminiTreeMuon collection is used to feed the miniTree producer.
Indeed, the master is for noRocherster minitree at the moment.
I will close this PR since is not fixing things. But I will remove the wRleading and wRsubleading muon collections from the selection_cff

Do you agree?

**Comment by skalafut** [comment]
Don't remove the wRleading and wRsubleading muon collections.  They are
used to build the dimon candidates, which are then used in the signal_mumu
and low dilepton mass region filters.


Regards,
Sean Kalafut

Physics PhD candidate
University of Minnesota Twin Cities

**Comment by shervin86** [comment]
wouldn't be better to use the wRminiTreeMuons in all the wr candidates?

**Comment by jec429** [comment]
wRminiTreeMuons (and wRminiTreeElectrons) should work just as well.

**Comment by skalafut** [comment]
The wr dilepton candidate objects are used in paths which will ultimately
be subjected to these cuts:

lead lepton pt > 60, sublead lepton pt >50, |lepton eta| < 2.4

we could use wRminiTreeMuon (and the analogous electrons collection)
instead of wRleadingMuon to make all wr candidates.  We would reach the
same results, but the minitrees (in particular the low dilepton mass
minitrees) would occupy more disk space.


Regards,
Sean Kalafut

Physics PhD candidate
University of Minnesota Twin Cities

**Pull request merged**
