### PR TITLE
Options for ToyThrower in analysis.cpp

### PR DESCRIPTION
**Pull request by skalafut**
modified analysis.cpp to accept a command line parameter to enable or disable systematics evaluation.  This was done to address issue 21.

### CODE REVIEW

**Comment by shervin86** [comment]
I have rebased w.r.t. master.
If syst is off, then ToyThrower is not called at all. 
The idea is to switch off the systematics, but some of the central values depend on ToyThrower, like Rochester and smearings for electrons, so the way it is implemented here is not correct.

@rchatter @previsualconsent @jec429  please review and double check that I'm right.

**Comment by skalafut** [comment]
I don't understand how systematics are applied in analysis.cpp.  To me,
running without systematics means turning ToyThrower off.  How should
systematics be disabled without turning ToyThrower off?


Regards,
Sean Kalafut

Physics PhD candidate
University of Minnesota Twin Cities

**Comment by shervin86** [comment]
For example erasing the systematic vector and making sure that ToyThower will run rochester and smearings

--
Shervin
Da: skalafut
Inviato: lunedì 2 maggio 2016 11:52
A: UMN-CMS/cms-WR
Rispondi a: UMN-CMS/cms-WR
Cc: Shervin Nourbakhsh; Comment
Oggetto: Re: [UMN-CMS/cms-WR] Temp issue twenty one (#28)


I don't understand how systematics are applied in analysis.cpp. To me,
running without systematics means turning ToyThrower off. How should
systematics be disabled without turning ToyThrower off?


Regards,
Sean Kalafut

Physics PhD candidate
University of Minnesota Twin Cities

**Comment by skalafut** [comment]
Thanks Shervin, I will do this.


Regards,
Sean Kalafut

Physics PhD candidate
University of Minnesota Twin Cities

**Comment by shervin86** [comment]
Anyway double check with @jec429  and @rchatter

**Comment by skalafut** [comment]
Will do.


Regards,
Sean Kalafut

Physics PhD candidate
University of Minnesota Twin Cities

**Comment by skalafut** [comment]
Until now we have always run these systematics with analysis.cpp:

[1] Smear_Muon_Scale
[2] Smear_Muon_ID_Iso
[3] Smear_Jet_Scale
[4] Smear_Electron_Scale

When systematics are disabled, do we want to disable [1] through [3], and
run [4]?  If you could talk over the phone that would be great, I don't
know how to proceed.


Regards,
Sean Kalafut

Physics PhD candidate
University of Minnesota Twin Cities

**Comment by shervin86** [comment]
I will call you

--
Shervin
Da: skalafut
Inviato: lunedì 2 maggio 2016 15:30
A: UMN-CMS/cms-WR
Rispondi a: UMN-CMS/cms-WR
Cc: Shervin Nourbakhsh; Comment
Oggetto: Re: [UMN-CMS/cms-WR] Temp issue twenty one (#28)


Until now we have always run these systematics with analysis.cpp:

[1] Smear_Muon_Scale
[2] Smear_Muon_ID_Iso
[3] Smear_Jet_Scale
[4] Smear_Electron_Scale

When systematics are disabled, do we want to disable [1] through [3], and
run [4]? If you could talk over the phone that would be great, I don't
know how to proceed.


Regards,
Sean Kalafut

Physics PhD candidate
University of Minnesota Twin Cities

**Comment by previsualconsent** [comment]
@rchatter Rajdeep will take a look at this, unless something else has been done in the last 2 days.

**Comment by skalafut** [comment]
Ok that sounds good.  I haven't touched this during the last 2 or 3 days.


Regards,
Sean Kalafut

Physics PhD candidate
University of Minnesota Twin Cities

**Comment by rchatter** [comment]
I have almost modified analysis.cpp for the central values, such that nToys = 1 will be a proxy for a run with no systematics.

This involves for muons:
throwing rochester(with a pre-defined seed), checking for consitency of the results later.
All Trg, ID, ISO efficiencies will use the central values 

I have the following question for the electrons:
Do the electrons need to be smeared at all for the central values?

Once I know this I will submit the modified master and Toythrower in a separates branch to be merged to master.
thanks,
Rajdeep

**Comment by shervin86** [comment]
Electrons have to be smeared.

**Comment by previsualconsent** [comment]
closing in favor of #46

**Pull request closed without merging**
