### PR TITLE
Temp sean april twenty sixteen

### PR DESCRIPTION
**Pull request by skalafut**
updates to analysis.cpp, Selector.h and Selector.cc, and miniPlotterForDYTandP.C.

NOTE the cross section normalization for MC in analysis.cpp is disabled, and ToyThrower is also disabled in analysis.cpp.

### CODE REVIEW

**Comment by previsualconsent** [comment]
So this PR doesn't have a full working version of analysis.cpp
How about pushing fixes for  #19 and #21 to this branch?

Which fixes have been addressed in this PR?

**Comment by skalafut** [comment]
I've been the only person using analysis.cpp for the last few weeks, and
the version in tempSeanAprilTwentySixteen does everything that is done in
the master branch plus some additional features.  I would like to have
"--isTagAndProbe" and the chainNames class in analysis.cpp.


Regards,
Sean Kalafut

Physics PhD candidate
University of Minnesota Twin Cities

**Comment by skalafut** [comment]
Peter what do you mean by "working"?  I can run analysis.cpp over the
newest minitrees and analyze the tagandprobe or signal trees.


Regards,
Sean Kalafut

Physics PhD candidate
University of Minnesota Twin Cities

**Comment by previsualconsent** [comment]
it has ToyThrower commented out still?

**Comment by shervin86** [comment]
this PR is based on #15 
Can someone review that and sign off for merging?
Then we can review this

**Comment by shervin86** [comment]
a version of this branch rebased w.r.t. #15 is here: tempSeanAprilTwentySixteenRebase
Todo:
 - ToyThrower should not be commented
 - event weights should be reviewed

**Comment by shervin86** [comment]
now rebased w.r.t. #23 
Superseeded by #24

**Pull request closed without merging**
