### PR TITLE
Modifications for central results when run with nToys = 1

### PR DESCRIPTION
**Pull request by rchatter**
nToys = 1 should give central values.

analysis.cpp modified to use central values of Mu ID/ISO efficiencies and not smear for Jet Energy scale systematics.
Rochester correction are done with a well defined seed.
Electron smearing is still deactivated in Toy Thrower(Why ??)
Ran thrice for MC(Powheg, SHv15NoRoch). But the same SHv15NoRoch dont seem to exist for data?

### CODE REVIEW

**Comment by previsualconsent** [comment]
could we make analysis.cpp do

First loop: do central values + statToys See #38 
Subsequent loops: do syst toys.
That way both results will be in the output file.

**Comment by rchatter** [comment]
For stat toys you want to throw Poissonian weights right?

On Mon, May 9, 2016 at 12:09 PM, Peter Hansen <notifications@github.com>
wrote:

> could we make analysis.cpp do
>
> First loop: do central values + statToys See #38
> <https://github.com/UMN-CMS/cms-WR/issues/38>
> Subsequent loops: do syst toys.
> That way both results will be in the output file.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/UMN-CMS/cms-WR/pull/46#issuecomment-217926384>
>



-- 


Rajdeep.Mohan.Chatterjee
Post Doctoral Fellow
School of Physics and Astronomy
University of Minnesota
115 Union Street Street SE
Minneapolis MN 55455
USA

**Comment by previsualconsent** [comment]
I am varying the fit parameter with its uncertainty and recalculating the integrals in each window.

https://github.com/UMN-CMS/cms-WR/commit/05a01e80a63e5b28f0726b89ce441966e8ac4215

**Comment by rchatter** [comment]
So this is done about the "central value" from analysis.cpp right?
So instead of a loop of central value, then stat toys and then syst toys,
would it be quicker if when nToys = 1 a loop is activated where the fitting
is done after selecting the events in analysis.cpp ?

On Mon, May 9, 2016 at 12:13 PM, Peter Hansen <notifications@github.com>
wrote:

> I am varying the fit parameter with its uncertainty and recalculating the
> integrals in each window.
>
> 05a01e8
> <https://github.com/UMN-CMS/cms-WR/commit/05a01e80a63e5b28f0726b89ce441966e8ac4215>
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/UMN-CMS/cms-WR/pull/46#issuecomment-217927433>
>



-- 


Rajdeep.Mohan.Chatterjee
Post Doctoral Fellow
School of Physics and Astronomy
University of Minnesota
115 Union Street Street SE
Minneapolis MN 55455
USA

**Comment by previsualconsent** [comment]
This should be able to be merged now.

**Comment by shervin86** [comment]
I don't understand the change in the makefile, but for the time being it's ok. Merging.

**Comment by previsualconsent** [comment]
The makefile changes allowed me to type make -j 10 when compiling. It was failing because signalPdf.exe depends on $(MODULES) but it wasn't in the dependencies. Also, lib/*.o also looked for a rule to build a file called "lib/*.o" which bothered me.

**Comment by previsualconsent** [comment]
Just a note. 

the TTree "tf1" has been renamed to "syst_tree"
I added two more trees.
"central_value_tree" and "stat_tree".

I hope the names are self explanatory.

**Pull request merged**
