### PR TITLE
Dev ttbar estimate

### PR DESCRIPTION
**Pull request by skalafut**
updated analysis.cpp and added a macro to the test directory to calculate the EE/EMu and MuMu/EMu TTBar scale factors.  Also added instructions to the doc directory so that everyone can run this workflow.

### CODE REVIEW

**Comment by shervin86** [comment]
I have not checked the code, I have fixed the documentation.
@jec429 @previsualconsent @rchatter please review and sign with +1.

**Comment by shervin86** [comment]
Nobody has reviewed this PR, what should I do? Should I rebase it?

**Comment by jec429** [comment]
Sorry I missed the message. +1

**Comment by skalafut** [comment]
rebased dev_ttbar_estimate with respect to current master (May 27th). Please merge this PR.

**Comment by shervin86** [comment]
merged into mergeShervin

**Pull request closed without merging**
